/**
 * @tai42/api-client — the typed transport for the tai42-skeleton HTTP API.
 *
 * One zod schema per consumed endpoint; every response is
 * validated and every failure throws. No caching of its own — server state
 * lives in TanStack Query in the feature packages.
 */
export { createApiClient, isSafeApiPath } from './client';
export type {
  ApiClient,
  RunToolArgs,
  StartConnectArgs,
  ApiKeyBody,
  ClaimLinkBody,
  ValidateConditionBody,
  TopicVerifierBody,
  TriggerLinkCreateBody,
  WebEntryCodeMintBody,
  AddUrlToScopeBody,
  RoleCreateBody,
  RoleUpdateBody,
  PinRoutePublicBody,
  CreatePresetBody,
  SavePresetVersionBody,
  ValidatePresetBody,
  ToolMetaPatch,
  StorageUploadBody,
  ConversationThreadFilters,
  ConversationTranscriptQuery,
  ConversationMessageSearchQuery,
  ConversationThreadMessageBody,
  MetricsQuery,
  RunsQuery,
  MarketplaceSearchQuery,
  MarketplaceInstallBody,
  MarketplaceInstallPreviewBody,
  MarketplaceUninstallBody,
} from './client';
export type { ApiConfig, RequestOptions } from './http';
export { apiRequest, apiText, apiDownload } from './http';
export {
  ApiError,
  ApiUnauthorizedError,
  ApiConflictError,
  ApiLoginFailedError,
  ApiSchemaError,
} from './errors';
export { SseFrameParser, readSseFrames } from './sse';
export type { SseFrame } from './sse';
export { parseAgentFrame, parseAgentTranscript, agentEventSchema } from './agents';
export type { AgentSummary, AgentEvent, UnknownAgentEvent, ParsedAgentEvent } from './agents';
export {
  toolRunStatus,
  toolRunSubmitResult,
  toolRunRecord,
  toolRunListItem,
  toolRunList,
  isTerminalRunStatus,
} from './tool-runs';
export type {
  ToolRunStatus,
  ToolRunSubmitResult,
  ToolRunRecord,
  ToolRunListItem,
  SubmitToolRunArgs,
} from './tool-runs';
export { summarizeFleetResult, summarizeFleetFanout, isFleetReportFailure } from './fleet-report';
export type {
  FleetReportSummary,
  FleetReportStatus,
  FleetWorkerFailure,
  FleetFailureOutcome,
} from './fleet-report';
export * as schemas from './schemas';
export type {
  ToolSchema,
  ToolMediaResult,
  ToolTagEntry,
  AuthRoute,
  RouteAction,
  GrantLevel,
  RoleGrants,
  RoleBody,
  RoleVersion,
  RoleAuditEvent,
  RoleVersions,
  PresetRecord,
  PresetDetail,
  PresetBody,
  PresetVersion,
  PresetRenamed,
  PresetReferees,
  PresetValidation,
  PresetVersionTags,
  PresetExtensionElement,
  FolderRecord,
  ToolMetaRecord,
  ToolMetaOverlay,
  PolicyBody,
  PolicyVersion,
  ValidateConditionResult,
  Extension,
  ToolExtensions,
  ToolExtensionsApplyResult,
  ProviderView,
  ConnectorCategoryView,
  ProviderCatalogResponse,
  ConnectorRef,
  ManifestMcpEntry,
  McpEnvRef,
  McpEnvRefs,
  ConnectionView,
  OAuthCompleteResult,
  StudioPluginManifest,
  Interaction,
  InteractionAnswered,
  InteractionsPage,
  InteractionMediaItem,
  MediaKind,
  AnswerFormat,
  Channels,
  ConversationDoor,
  ConversationTargetKind,
  ConversationMode,
  ConversationDeliveryStatus,
  ConversationAnswerStatus,
  ConversationRoute,
  ConversationRoutes,
  ConversationRouteCreate,
  ConversationRouteWritten,
  ConversationRouteDeleted,
  ConversationThread,
  ConversationThreadsPage,
  ConversationMessage,
  ConversationRecordOrigin,
  TranscriptOrder,
  ConversationTranscriptPage,
  ConversationMessageSearchPage,
  ConversationThreadMode,
  ConversationThreadModeState,
  ConversationThreadMessageSent,
  TargetConversationConfig,
  ConversationConfigs,
  ConversationConfigWritten,
  ConversationConfigDeleted,
  ConversationFailedMessages,
  ConversationThreadDeleted,
  ConversationPersonDeleted,
  WebEntryCode,
  WebEntryGate,
  WebEntryGateState,
  WebEntryCodeMinted,
  WebEntryCodeRevoked,
  Notification,
  Notifications,
  ChannelTemplate,
  HookParams,
  HookList,
  TriggerAuth,
  SettingsSchema,
  TokensPayload,
  LoginFormField,
  LoginMethod,
  LoginMethods,
  LoginResult,
  MeProjection,
  RouteEntry,
  PatternEntry,
  SubMcpEntry,
  SubMcpMount,
  ClaimLinkCreated,
  TriggerLinkCreated,
  TriggerLinkRecord,
  TriggerLinkList,
  TriggerLinkDeleted,
  LogoutResult,
  AuthCapabilities,
  BackupDocument,
  BackupImportReport,
  ScheduleItem,
  StorageInfo,
  StorageResourceStat,
  BackendInfo,
  WorkerKind,
  WorkerState,
  WorkerLastOp,
  FleetWorker,
  FleetWorkers,
  FleetOutcome,
  FleetWorkerResult,
  FleetResult,
  FleetReloadResult,
  FleetReportFanout,
  ReloadConfigResult,
  McpReloadResult,
  KindStatus,
  DashboardMetrics,
  Run,
  RunSpan,
  RunTrace,
  MarketplaceItem,
  MarketplaceDelivery,
  MarketplaceSource,
  MarketplaceRequiredEnvVar,
  MarketplaceRouteDecl,
  MarketplaceRoutesDecl,
  MarketplaceSearchKind,
  MarketplaceSearchGroup,
  MarketplaceSearchRow,
  MarketplaceSearchPage,
  MarketplaceVersion,
  MarketplaceLatestVersion,
  MarketplaceAdvisory,
  MarketplacePluginDetail,
  MarketplaceInstalledCompat,
  MarketplaceInstalledPlugin,
  MarketplaceQuarantinedPlugin,
  MarketplaceInstalled,
  MarketplaceUpgradeAllRow,
  MarketplaceUpgradeAllResult,
  MarketplaceInstallResult,
  MarketplaceMountedRoute,
  MarketplacePreviewRoute,
  MarketplacePreviewItem,
  MarketplacePreviewCollision,
  MarketplacePreviewPublicRoute,
  MarketplaceInstallPreview,
  MarketplaceUninstallResult,
} from './schemas';
