/**
 * @tai42/api-client — the typed transport for the tai42-skeleton HTTP API.
 *
 * One zod schema per consumed endpoint; every response is
 * validated and every failure throws. No caching of its own — server state
 * lives in TanStack Query in the feature packages.
 */
export { createApiClient, isSafeApiPath } from './client';
export type {
  ApiClient,
  RunToolArgs,
  StartConnectArgs,
  ApiKeyBody,
  ClaimLinkBody,
  ValidateConditionBody,
  TopicVerifierBody,
  AddUrlToScopeBody,
  RoleCreateBody,
  RoleUpdateBody,
  PinRoutePublicBody,
  CreatePresetBody,
  SavePresetVersionBody,
  ValidatePresetBody,
  StorageUploadBody,
  MetricsQuery,
  RunsQuery,
  MarketplaceSearchQuery,
  MarketplaceInstallBody,
  MarketplaceUninstallBody,
} from './client';
export type { ApiConfig, RequestOptions } from './http';
export { apiRequest, apiText, apiDownload } from './http';
export {
  ApiError,
  ApiUnauthorizedError,
  ApiConflictError,
  ApiLoginFailedError,
  ApiSchemaError,
} from './errors';
export { SseFrameParser, readSseFrames } from './sse';
export type { SseFrame } from './sse';
export { parseAgentFrame, parseAgentTranscript, agentEventSchema } from './agents';
export type { AgentSummary, AgentEvent, UnknownAgentEvent, ParsedAgentEvent } from './agents';
export {
  toolRunStatus,
  toolRunSubmitResult,
  toolRunRecord,
  toolRunListItem,
  toolRunList,
  isTerminalRunStatus,
} from './tool-runs';
export type {
  ToolRunStatus,
  ToolRunSubmitResult,
  ToolRunRecord,
  ToolRunListItem,
  SubmitToolRunArgs,
} from './tool-runs';
export { summarizeFleetResult, summarizeFleetFanout, isFleetReportFailure } from './fleet-report';
export type {
  FleetReportSummary,
  FleetReportStatus,
  FleetOriginFailure,
  FleetFailureOutcome,
} from './fleet-report';
export * as schemas from './schemas';
export type {
  ToolSchema,
  ToolMediaResult,
  ToolTagEntry,
  AuthRoute,
  RouteAction,
  GrantLevel,
  RoleGrants,
  RoleBody,
  RoleVersion,
  RoleAuditEvent,
  RoleVersions,
  PresetRecord,
  PresetDetail,
  PresetBody,
  PresetVersion,
  PresetRenamed,
  PresetReferees,
  PresetValidation,
  PresetVersionTags,
  PresetExtensionElement,
  PolicyBody,
  PolicyVersion,
  ValidateConditionResult,
  Extension,
  ToolExtensions,
  ToolExtensionsApplyResult,
  ProviderView,
  ConnectionView,
  OAuthCompleteResult,
  StudioPluginManifest,
  Interaction,
  InteractionAnswered,
  InteractionMediaItem,
  MediaKind,
  AnswerFormat,
  Channels,
  Notification,
  Notifications,
  HookParams,
  SettingsSchema,
  TokensPayload,
  LoginFormField,
  LoginMethod,
  LoginMethods,
  LoginResult,
  MeProjection,
  RouteEntry,
  PatternEntry,
  SubMcpEntry,
  ClaimLinkCreated,
  LogoutResult,
  AuthCapabilities,
  BackupDocument,
  BackupImportReport,
  ScheduleItem,
  StorageInfo,
  StorageResourceStat,
  BackendInfo,
  OriginKind,
  FleetOrigin,
  FleetWorkers,
  FleetOutcome,
  FleetOriginResult,
  FleetResult,
  FleetReloadResult,
  FleetReportFanout,
  ReloadConfigResult,
  McpReloadResult,
  KindStatus,
  DashboardMetrics,
  Run,
  RunSpan,
  RunTrace,
  MarketplaceItem,
  MarketplaceSearchRow,
  MarketplaceSearchPage,
  MarketplaceVersion,
  MarketplaceLatestVersion,
  MarketplaceAdvisory,
  MarketplacePluginDetail,
  MarketplaceInstalledPlugin,
  MarketplaceInstallResult,
  MarketplaceUninstallResult,
} from './schemas';
